### ISSUE TITLE
Publish in crates.io?

### ISSUE THREAD

**Issue by zkanda** [jgavris/rs-git-fsmonitor#1]
Would be nice if we can easily do `cargo install rs-git-fsmonitor`.

Cheers and thanks for creating this tool.

**Comment by dyxushuai** [comment]
@zkanda Since the `rs-git-fsmonitor` depends on `watchman` from `brew`. So  I think `cargo install  ...` instead of `brew install ...` isn't a good choice.

**Comment by jgavris** [comment]
Indeed, `watchman` is doing the heavy lifting here, and using homebrew makes it easy to include that dependency. I haven't given thought to installing on other platforms yet.

**Comment by zkanda** [comment]
Indeed, I guess we can close this one. :)
