### ISSUE TITLE
while computing sockname: failed to create /usr/local/var/run/watchman/$USER-state

### ISSUE THREAD

**Issue by bbuchalter** [jgavris/rs-git-fsmonitor#15]
After installing via homebrew, running `git config core.fsmonitor rs-git-fsmonitor` and then `git status` I get the error:
```
2020-02-24T11:59:53,133: [0x1086cadc0] while computing sockname: failed to create /usr/local/var/run/watchman/brian.buchalter-state: No such file or directory
```

After running `mkdir -p /usr/local/var/run/watchman` the issue went away.

**Comment by jgavris** [comment]
Thanks for the report. `rs-git-fsmonitor` just shells out to `watchman`. The homebrew recipe installs `watchman` recipe as a dependency. I think other people have reported this issue on their project. https://github.com/facebook/watchman/issues/495
