### ISSUE TITLE
Getting "No such file or directory (os error 2)" error

### ISSUE THREAD

**Issue by lunemec** [jgavris/rs-git-fsmonitor#3]
I tried your project, but no luck:
```
 λ git clone https://github.com/jgavris/rs-git-fsmonitor.git
 λ cargo build --release
 λ sudo ln -s `pwd`/target/release/rs-git-fsmonitor /usr/bin/.
 λ git --global config core.fsmonitor rs-git-fsmonitor
 λ git st  # within git repo
No such file or directory (os error 2)
```

**Comment by lunemec** [comment]
Oh, so that is because it depends on watchman binary: https://github.com/facebook/watchman

**Comment by lunemec** [comment]
After installing watchman it works!

**Comment by jgavris** [comment]
Sorry about that! The happy (documented) path right now is to install with homebrew on macOS. I haven't added instructions for other platforms, pull requests welcome! I figure if you're brave enough to `cargo` you can figure it out.
