### ISSUE TITLE
Performance is not much better on the Chromium src repo, and a lot slower on a smaller repo

### ISSUE THREAD

**Issue by ndbroadbent** [jgavris/rs-git-fsmonitor#6]
I tried this on the Chromium source code: (I'm following [this guide](https://chromium.googlesource.com/chromium/src/+/master/docs/mac_build_instructions.md) to compile from source.) 

Before:

```
$ time git status > /dev/null

real	0m4.497s
user	0m1.749s
sys	0m10.431s
```

After running `git config core.fsmonitor rs-git-fsmonitor`:

```
$ time git status > /dev/null

real	0m2.386s
user	0m1.167s
sys	0m1.285s
```

It's a little bit faster, but I was expecting it to be close to zero, because I haven't changed any files.

I also tried the [original Perl script](https://github.com/git/git/blob/master/templates/hooks--fsmonitor-watchman.sample), and that's pretty much the same:

```
$ time git status > /dev/null

real	0m2.408s
user	0m1.173s
sys	0m1.284s
```

I also tried `rs-git-fsmonitor` on a relatively small repo, and saw slightly worse performance for `git status`.

Before:

```
$ time git status > /dev/null

real	0m0.067s
user	0m0.025s
sys	0m0.043s
```

After running `git config core.fsmonitor rs-git-fsmonitor`:

```
$ time git status > /dev/null

real	0m0.091s
user	0m0.033s
sys	0m0.041s
```
It might be good to add a note to the README about worse performance on small repos. Maybe something like "If `time git status` takes less than x seconds, you shouldn't use this tool."

Thanks!

**Comment by ndbroadbent** [comment]
Actually I opened this issue before I tried that original Perl script, and I just saw that the performance is pretty much the same. So definitely not an issue with `rs-git-fsmonitor`. Haha I was just hoping that commands would finish instantly when no files had changed.

**Comment by jgavris** [comment]
It's funny you should mention that, I have a couple macs and for some reason on one of them, enabling the monitor doesn't prevent all the `stat` calls that it does on the other 2. What we're seeing may be bug in `watchman` or `git`, as this script is very simple (but fast) glue code between those two programs.

I'd encourage you to try out `sudo dtruss git status` with the monitor enabled / disabled. When it's working correctly you should see almost no `stat` calls on the second call.

**Comment by ndbroadbent** [comment]
Oh that's really cool! I didn't know about `dtruss`. I also found the [Improving performance of git status](https://chromium.googlesource.com/chromium/src/+/master/docs/mac_build_instructions.md#Improving-performance-of) section, so the following commands really helped with performance:

```
sudo sysctl kern.maxvnodes=$((512*1024))

git update-index --test-untracked-cache
# => OK

git config core.untrackedCache true
```

After running those commands:

```
# Without rs-git-fsmonitor
$ time git status > /dev/null

real	0m0.996s
user	0m0.822s
sys	0m2.051s

$ git config core.fsmonitor rs-git-fsmonitor

$ time git status > /dev/null

real	0m0.591s
user	0m0.500s
sys	0m0.078s
```


And here's the `dtruss` results checking for `stat64` calls:

```
# Without rs-git-fsmonitor
$ sudo dtruss git status 2>&1 | grep stat64 | wc -l
# => 5311

$ git config core.fsmonitor rs-git-fsmonitor
$ sudo dtruss git status 2>&1 | grep stat64 | wc -l
# => 2593

$ sudo dtruss git status 2>&1 | grep stat64 | wc -l
# => 204

$ time git status > /dev/null

real	0m0.609s
user	0m0.518s
sys	0m0.081s
```

Thanks, this has been really interesting!

**Comment by jgavris** [comment]
I think you might be experiencing the bug I mentioned above...when it's working for real I see under 100 milliseconds.

```shell
2018-12-04 09:31:41 jgavris in ~/code/software on develop
λ sudo dtruss git status 2>&1 | grep stat64 | wc -l

    2563
2018-12-04 09:31:49 jgavris in ~/code/software on develop
λ git config core.fsmonitor rs-git-fsmonitor
2018-12-04 09:31:53 jgavris in ~/code/software on develop
λ sudo dtruss git status 2>&1 | grep stat64 | wc -l

     388
2018-12-04 09:31:56 jgavris in ~/code/software on develop
λ time git status
On branch develop
Your branch is up to date with 'origin/develop'.

nothing to commit, working tree clean

real	0m0.074s
user	0m0.039s
sys	0m0.031s
```
