### ISSUE TITLE
how to install from ubuntu18.04?

### ISSUE THREAD

**Issue by rex1031** [jgavris/rs-git-fsmonitor#7]
how to install from ubuntu18.04?

**Comment by jgavris** [comment]
I don't run Ubuntu, but this should probably work. Could you try it out? I'll add it to the readme if it does.

1. Install Rust https://www.rust-lang.org/tools/install.
2. Build / install `rs-git-fsmonitor` to `/usr/local/bin`: `cargo install --path . --root /usr/local`.
3. Install `watchman` https://medium.com/@saurabh.friday/install-watchman-on-ubuntu-18-04-ba23c56eb23a.
4. Configure the monitor (from the directory of the repo you want to enable it for): `git config core.fsmonitor rs-git-fsmonitor`.

**Comment by themightychris** [comment]
@rex1031 the habitat package that just got merged from my PR is a great path for deploying on any Linux system

You can build yourself on Linux via habitat by cloning the repo and just running `hab pkg build .` within it
